@startuml

skin rose

abstract class Compte {
  - email : String {id}
  - motDePasse : String
  - numAdresseCompte : int
  - rueCompte : String
  - villeCompte : String
  - codePostalCompte : int
  - telephone : String
  +(abstract) modifierCompte() : void
}

class CompteMembre {
  - nomMembre : String
  - prenomMembre : String
  - pseudo : String
  + modifierCompte() : void
}


class CompteProfessionnel {
  - denomination : String
  + modifierCompte() : void
}

class ProfessionnelPrive {
  - SIREN : String
  - IBAN : String {optional}
  + modifierCompte() : void
}

ProfessionnelPrive --|> CompteProfessionnel

CompteMembre --|> Compte
CompteProfessionnel --|> Compte

abstract class Offre {
  # idOffre : String {id}
  # nomOffre : String
  # numAdresseOffre : int
  # rueOffre : String
  # villeOffre : String
  # codePostalOffre : int
  # resume : String
  # nomCat : String
  # noteOffre : float
  # dateDebut : Date
  # dateFin : Date
  # enLigne : boolean
  # datePublication : Date
  # derniereMaj : Date
  + mettreHorsLigne() : void
  + estOuvert() : boolean
  + compterAvis() : int
}

note right of Offre
- codePostalOffre commence par 22, 29, 35, 44, 56
- noteOffre >= 0
- dateFin >= dateDebut
- datePublication < dateFin
- derniereMaj >= datePublication
end note

class ImageOffre {
  - urlVersImage : String {id}
}

Offre "1" -- "1..*" ImageOffre: Illustre

abstract class Categorie {
  - idOffre : String {id}
}

class Activite{
  - ageRequis : int
  - dureeActivite : String
}

note left of Activite:- ageRequis >= 0

class Prestation {
  - idPresta : String {id}
  - nomPrestation : String
  - descriptionPresta : String
  - prixPresta : float
}
note left of Prestation:- prixPresta >= 0

Activite "1" -- "0..*" Prestation : PrestaProposées

class Visite {
  - dureeVisite : String
  - estGuidee : boolean
}

class Langue {
  - nomLangue : String {id}
}

Visite "0..*" -- "0..*" Langue : LanguesProposées

class Spectacles {
  - dureeSpectacle : String
  - placesSpectacle : int
}
note left of Spectacles:- placesSpectacle > 0

class ParcAttraction {
  - urlVersPlan : String
  - nbAttractions : int
}
note left of ParcAttraction:- nbAttractions > 0

class Attraction {
  - idAttraction : String
  - nomAttraction : String
  - ageMinAttraction : int
}

ParcAttraction "1..*" -- "1" Attraction : AttractionsProposees

class Restauration {
  - urlVersCarte : String
  - gammePrix : String
  - RepasServis : String
}

Categorie <|-- Activite
Categorie <|-- Visite
Categorie <|-- Spectacles
Categorie <|-- ParcAttraction
Categorie <|-- Restauration

Offre "0..*" -- "1" Categorie

class OffrePayanteStandard {
  - option : String
  - optionActive : boolean
  + activerOption() : void
  + desactiverOption() : void
  + calculerPrix() : float
}

class Tarif {
  - nomTarif : String
  - prixTarif : float
}
note right of Tarif:- prixTarif >= 0

Offre "1" -- "1..*" Tarif : grilleTarifaire


class OffrePremium {
  - blacklistDispo : int {0 <= blacklistDispo <= 3}
}
note right of OffrePremium:- 0 <= blacklistDispo <= 3

OffrePayanteStandard --|> Offre
OffrePremium --|> OffrePayanteStandard

class Avis {
  - idAvis : String {id}
  - messageA : String
  - note : int
  - nbLike : int
  - nbDislike : int
  - estConsulte : boolean
  - blacklist : boolean
  - estSiganle : boolean
  + signalerAvis() : void
  + supprimerAvis() : void
}
note right of Avis
- 1  <= note <= 5
- nbLike >= 0
- nbDislike >= 0
end note

class Reponse {
  - idRep : String {id}
  - messageRep : String
  + repondreAvis(message : String) : void
  + supprimerReponse() : void
}

CompteProfessionnel "1" -- "0..*" Offre : Propose
CompteMembre "1" -- "0..*" Avis : Donne
Avis "0..*" -- "1" Offre : Concerne

CompteProfessionnel "1" -- "0..*" Avis
(CompteProfessionnel, Avis) .. Reponse

class Facture {
  - numFacture : String {id}
  - prixFacture : float {prixFacture > 0}
  - dateFacturation : Date
}
note right of Facture:- prixFacture >= 0

Facture "1..*" -- "1" OffrePayanteStandard: FacturationConcerne
Facture "0..*" -- "1" ProfessionnelPrive : ReglementFacture

@enduml
