@startuml

skin rose

abstract class Compte {
  - email : String {id, frozen}
  - motDePasse : String
  - numAdresseCompte : int
  - rueCompte : String
  - villeCompte : String
  - codePostalCompte : int
  - telephone : String
  +(abstract) modifierCompte() : void
}

class CompteMembre {
  - nomMembre : String
  - prenomMembre : String
  - pseudo : String
  + modifierCompte() : void
}


class CompteProfessionnel {
  - denomination : String
  + modifierCompte() : void
}

class ProfessionnelPrive {
  - SIREN : String
  - IBAN : String {optional}
  + modifierCompte() : void
}

ProfessionnelPrive --|> CompteProfessionnel

CompteMembre --|> Compte
CompteProfessionnel --|> Compte

abstract class Offre {
  # idOffre : String {id}
  # nomOffre : String
  # numAdresseOffre : int
  # rueOffre : String
  # villeOffre : String
  # codePostalOffre : int {code postal starts with 22, 29, 35, 44, 56}
  # prix : float {prix > 0}
  # resume : String
  # nomCat : String
  # noteOffre : float {noteOffre > 0}
  # dateDebut : Date
  # dateFin : Date {dateFin > dateDebut}
  # enLigne : boolean
  # datePublication : Date
  # derniereMaj : Date
  + mettreHorsLigne() : void
  + estOuvert() : boolean
  + compterAvis() : int
}

class ImageOffre {
  - urlVersImage : String {id}
}

Offre "1" -- "1..*" ImageOffre: Illustre

class Activite{
  - ageRequis : int
  - dureeActivite : String
}

class Prestation {
  - idPresta : String {id}
  - nomPrestation : String
  - descriptionPresta : String
  - prixPresta : float
}

Activite "1" -- "0..*" Prestation : PrestaProposées

class Visite {
  - dureeVisite : String
  - estGuidee : boolean
}

class Langue {
  - nomLangue : String {id}
}

Visite "0..*" -- "0..*" Langue : LanguesProposées

class Spectacles {
  - dureeSpectacle : String
  - placesSpectacle : int
  
}

class ParcAttraction {
  - urlVersPlan : String
  - nbAttractions : int
}

class Attraction {
  - idAttraction : String
  - nomAttraction : String
  - ageMinAttraction : int
}

ParcAttraction "1..*" -- "1" Attraction : AttractionsProposees

class Restauration {
  - urlVersCarte : String
  - gammePrix : String
  - RepasServis : String
}

Offre <|-- Activite
Offre <|-- Visite
Offre <|-- Spectacles
Offre <|-- ParcAttraction
Offre <|-- Restauration

class OffrePayanteStandard {
  - option : String
  - optionActive : boolean
  + activerOption() : void
  + desactiverOption() : void
  + calculerPrix() : float
}

class Tarif {
  - nomTarif : String
  - prixTarif : float {prix > 0}
}

Offre "1" -- "1..*" Tarif : grilleTarifaire


class OffrePremium {
  - blacklistDispo : int {0 <= blacklistDispo <= 3}
}

OffrePayanteStandard "0..*" -- "1" Offre
OffrePremium --|> OffrePayanteStandard


class Avis {
  - idAvis : String {id}
  - messageA : String
  - note : int {1  <= note <= 5}
  - nbLike : int
  - nbDislike : int
  - estConsulte : boolean
  - blacklist : boolean
  - estSiganle : boolean
  + signalerAvis() : void
  + supprimerAvis() : void
}

class Reponse {
  - idRep : String {id}
  - messageRep : String
  + repondreAvis(message : String) : void
  + supprimerReponse() : void
}

CompteProfessionnel "1" -- "0..*" Offre : Propose
CompteMembre "1" -- "0..*" Avis : Donne
Avis "0..*" -- "1" Offre : Concerne

CompteProfessionnel "1" -- "0..*" Avis
(CompteProfessionnel, Avis) .. Reponse

class Facture {
  - numFacture : String {id}
  - prixFacture : float {prixFacture > 0}
  - dateFacturation : Date
}

Facture "1..*" -- "1" OffrePayanteStandard: FacturationConcerne
Facture "0..*" -- "1" ProfessionnelPrive : ReglementFacture

@enduml
